// <auto-generated />
namespace ClothesWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateorder6h13 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateorder6h13));
        
        string IMigrationMetadata.Id
        {
            get { return "202406271113289_updateorder6h13"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
