// <auto-generated />
namespace ClothesWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateorder6h11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateorder6h11));
        
        string IMigrationMetadata.Id
        {
            get { return "202406271112198_updateorder6h11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
